argoconfig:
  # -- Choose between `applicationSet` and `application` to influence what get's rendered.
  # If you use `applicationSet` you also need to configure `argoconfig.generators` or individual
  # generators for apps.
  mode: "application"
  application:
    # -- Optional annotations to add to all Applications metadata.
    annotations: {}
  applicationSet:
    # -- Generators to use for ApplicationSets.
    # These get merged with the generator from individual components to generate the final generators.
    generators: []

# -- [Argo CD Notifications](https://argocd-notifications.readthedocs.io/en/stable/) is DEPRECATED, use Argo CD directly instead.
# @default -- DEPRECATED
argocdNotifications:
  enabled: false
  name: argocd-notifications
  annotations: {}
  destination:
    namespace: "infra-argocd"
  repoURL: "https://argoproj.github.io/argo-helm"
  chart: "argocd-notifications"
  targetRevision: "1.8.*"
  values: {}

# -- [Argo Rollouts](https://argoproj.github.io/argo-rollouts/) ([example](./examples/argo-rollouts.yaml))
# @default -- -
argoRollouts:
  # -- Enable Argo Rollouts
  enabled: false
  name: argo-rollouts
  # -- Annotations for Argo Rollouts app
  annotations: {}
  destination:
    # -- Namespace
    namespace: "infra-argo-rollouts"
  # -- Repo URL
  # @default -- [repo](https://argoproj.github.io/argo-helm)
  repoURL: "https://argoproj.github.io/argo-helm"
  # -- Chart
  chart: "argo-rollouts"
  # -- [argo-rollouts Helm chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-rollouts) version
  targetRevision: "2.18.*"
  # -- Helm values
  # @default -- [upstream values](https://github.com/argoproj/argo-helm/blob/master/charts/argo-rollouts/values.yaml)
  values: {}
  # -- Generators to ApplicationSet
  # If `argoconfig.mode` is set to `applicationSet` this gets merged with `argoconfig.generators` to generate the
  # the generators for this application.
  generators: []
